docs/guide/ecosystem/desktop-apps.md
Adding a desktop apps chapter to ecosystem section
=> Desktop apps

docs/guide/community/diversity.md
This includes changing the title to Diversity and Inclusion
=> Rewrite diversity based on Jen Looper version

docs/guide/ecosystem/ui-libraries.md
TODO:
- how to chose UI library (bullet points available)
- Tailwind (only stub)
=> Add initial content of UI libraries

docs/guide/ecosystem/hosting.md
=> chore: fix typos, capitalization, phrasing of hosting

docs/.vuepress/config.js, docs/multilingual/spanish.md
Adds multiingual resources dropdown to the app. Allows #12 to be continued on top.
=> feat: add multi-lingual content section.

docs/guide/ecosystem/server-side-rendering.md, docs/guide/learning/faq.md
Adds content to the FAQ page. This page will just continue to grow, but I think this is a good starting point.
Closes #15
=> Add content to FAQ page

docs/guide/README.md
I did some standarization and scope changes, but it's all up for discussion, both overall and on individual cases. Don't treat them like my final recommendations, I'm not fully happy with this suggestions either.
It's more to signify that the sitemap content needs edits.
Maybe we should just list all the sections of each chapter here.
And maybe it should be just an issue with discussion.
=> Rewrite sitemap descriptions

docs/guide/ecosystem/documentation.md
As promised, here is the PR.
I hope I did not overstep here. I will remove doc about vuese if you prefer the authors to document it themselves.
You should probably ask the authors of the two other libraries to review.
霍 春阳 for vuese 
& 
Viljami Salminen for vue-design-system
Related to #25
=> add description for styleguidist vuese and vue-design-system

docs/guide/learning/how-to-learn-vue.md
Basic AngularJs block for Coming from other technology
To see if the style and content is okay before proceeding with Polymer
=> chore: Angularjs section for other tech block

docs/guide/ecosystem/mobile-apps.md
=> Improve mobile apps

docs/.vuepress/config.js, docs/guide/ecosystem/i18n.md
Adds i18n page with description of the most popular packages.
Closes #31
=> Add i18n page

docs/guide/community/meetups.md, docs/guide/ecosystem/client-server-communication.md, docs/guide/ecosystem/documentation.md, docs/guide/ecosystem/server-side-rendering.md, docs/guide/ecosystem/static-site-generators.md, docs/guide/learning/books.md, docs/guide/learning/faq.md, docs/guide/learning/tips-from-mentors.md, docs/guide/learning/workshops.md
Just found a few more, you can reject the one from AbarthMono (Also me)
=> [Fix] Corrected some typos in the documentation

docs/guide/ecosystem/desktop-apps.md
You guys were pointing to one of my experimental repo's. I've since created a much more stable/normal boilerplate with all the stuff you'd want in a regular project.
* Vue-CLI compatible
* Vue-DevTools built in to NW.js
* Automated NW.js builds for distribution
* Vue build settings to only target the latest Chromium version
=> Changed NW.js boilerplate

docs/.vuepress/config.js, docs/guide/README.md, docs/guide/ecosystem/editors-and-tools.md
This PR adds basic info about IDEs and tools for Vue Development. 
The idea is to expose the most popular solutions and guide people towards what to choose. We are getting lots of questions on whats "best", we should not answer that, but at least guide them towards an answer.
In the Tools section I will explain very very briefly about ESLint and Prittier, and where the confusion comes from whem using them together and how to resolve it + some nice articles on the matter. Do you have any other tools we could add here?
Please take a look and tell me if the direction is right for you.
Closes #34
=> Add initial Editors and Tools page

docs/guide/ecosystem/boilerplates.md
I just updated the github url 👍
=> docs(boilerplates): update link to vuesion

docs/multilingual/spanish.md
I started creating a course with some basic concepts, and the content is in Spanish.
=> Adding a Spanish Introductory mini course on Vue

docs/guide/learning/courses.md
I created a playlist on a YouTube channel where I develop step by step a desktop app using NW.js + Vuetify.
I hope this can be of help to more people trying to get a feel for how it would be to use them together!
Opened this PR after #80 's feedback.
=> Adding a video series for NW.js + Vue

docs/guide/ecosystem/forms.md
updated description for vee-validate due to the release of `3.0` which uses components with scoped slots instead of directives.
Also added a note on the localized validation messages due to it being an important feature of vee-validate.
=> Updated vee-validate description - Forms

docs/guide/ecosystem/static-site-generators.md
This PR addresses issue #106 
- added summaries for Sabre and Poi + vue-static
=> added summaries to the Summary (TLDR) section

docs/guide/ecosystem/ui-libraries.md
Changes have been made according to the feedback from @gustojs.
Can you please review them?
Thank you!
=> Changed Inkline description to be more objective

docs/guide/learning/courses.md
> Simple and beginner friendly tutorial for getting started with Vuejs 
> 
> This youtube series covers the entire basics of Vuejs and important topics such as the Vue Instance, Event Listeners, Data binding, Life cycle Hooks and Setting up the vue-router plugin.
=> Rephrased my Addition

docs/guide/ecosystem/client-server-communication.md
added 'contribute' sections to places that didn't have them already but clearly need contributions!
=> Housekeeping change to client-server-communication.md

docs/guide/community/vue-3.md, docs/guide/learning/books.md, docs/guide/learning/learning-platforms.md
👋 I released an ebook and its companion learning platform yesterday. It's about Vue 3! I've been contributing to the framework and some tools (the CLI, VTU) for some time.
I don't know if you want to have a separate section in the Books page for the ones dedicated to Vue 3, so I've put it at the bottom. 
You can check out more details at books.ninja-squad.com/vue 
Let me know if that's OK, thank you!
=> feat: Add Become a Ninja with Vue 3

docs/guide/ecosystem/ui-libraries.md
VueSax description was primarily focused on the fact that it's still experimental, which is no longer a case.
=> Update VueSax UI library

docs/guide/ecosystem/forms.md
Update to current Vuelidate links
=> Update Vuelidate links

docs/guide/ecosystem/ui-libraries.md
https://www.primefaces.org/primevue/
=> Add PrimeVue

docs/guide/ecosystem/ui-libraries.md
Hi, I wanted to add Kendo UI for Vue to the Components list - please let me know if have missed anything.
Greetings,
Plamen
=> Add kendo UI

docs/guide/community/vue-3.md, docs/guide/learning/books.md
Added "Vue - The Road To Enterprise" link to the Vue 3 related books section
Added "Vue - The Road To Enterprise" section to the learning books section.
=> Add "Vue - The Road To Enterprise" book

docs/guide/ecosystem/server-side-rendering.md
fixes grammatical mistakes on the SSR page of the Vue documentation.
=> fix(documentation): grammatical errors on SSR page
